#!/bin/sh /etc/rc.common

SERVICE_DAEMONIZE=1

START=99zz

start()
{
	#local version=`getfirm SOFTVERSION|awk '{print $3}'`
	#local curTime=${version:0-3:4}'-'${version:4-5:2}'-'${version:6-7:2}
	#date -s $curTime" 00:00:00"
	
	service_start /usr/bin/cloud-brd -c /etc/cloud_config.cfg
}

stop()
{
	SERVICE_SIG=kill service_stop /usr/bin/cloud-brd
}

restart()
{
	stop
	start
}
